### ISSUE TITLE
Lock pick problems

### ISSUE THREAD

**Issue by MasterEnderman** [Boundarybreaker/Locky#1]
The localization of the lock pick seems broken. it also doesn't have a recipe instead there are two recipes for the lock.

![image](https://user-images.githubusercontent.com/24524662/50740949-ebf77180-11f6-11e9-82ea-8b6b15b8ceca.png)

![image](https://user-images.githubusercontent.com/24524662/50740954-f9146080-11f6-11e9-8fda-9067fa1d3820.png)

**Comment by LemmaEOF** [comment]
Ah, I forgot the underscore in the lang, and probably made a typo in the recipe. Fixing now!
