### ISSUE TITLE
The players in creative mode can ues Lock picks remove the lock.

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Boundarybreaker/Locky#3]
If gamerule locky:creativeLockBypass is false , then players in  creative mode can not open lock block,but  players in  creative mode can ues Lock picks remove the lock. 
1. If gamerule locky:creativeLockBypass is false , then players in  creative mode can not ues Lock picks remove the lock.  Unless name the lock pick the same as the container's lock.

**Comment by LemmaEOF** [comment]
This is intended behavior, but I *should* honestly put it under the gamerule.
